### ISSUE TITLE
Can't see ci/sideci errors

### ISSUE THREAD

**Issue by nishina555** [shu0115/minimum-omniauth-scaffold#16]
When I created pull request, sideci's check was failed but I couldn't see the detail of the errors.
How can contributors see the information?

**Comment by shu0115** [comment]
sideciが勝手に見ちゃってるみたいだったので、一旦sideciの管理対象から外してみました。
(エラー自体は「解析ツールがサポートしていないプラットフォーム」というものでした)

**Comment by nishina555** [comment]
@shu0115 なるほど。ご丁寧に回答ありがとうございました。
